name: fun_components
description: Polymer components made for fun
dependencies:
  credit_cat: any
  markdown: any
  polymer: any
  roman_numerals: any
  turkish_numbers: any
dev_dependencies:
  scheduled_test: any
